brew "coreutils"
brew "wget"
brew "git"
brew "tree"
brew "neovim"
brew "fzf"
brew "htop"
brew "tldr"
brew "tmux"
brew "gpg"
brew "zsh"
brew "zplug"
brew "tig"
brew "node"
brew "git-lfs"
brew "pyenv"
brew "pyenv-virtualenv"
brew "reattach-to-user-namespace"

cask_args appdir: "/Applications"
tap "homebrew/cask"
cask "alacritty"
cask "google-chrome"
cask "firefox"
